name: Main Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
jobs:
  test_suite: 
      runs-on: ubuntu-20.04 # Choosing OS
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node -v
      - run: npm ci
      - run: npm install -g newman
      - run: npm i -g allure-commandline
 
      - name: Generate Report
        if: always()
        run: npm run allure:report # Name of the allure generate script
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results                    
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report       
      - name: Deploy report
        uses: JamesIves/github-pages-deploy-action@4.1.4
        if: always()
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.